<ToolPaletteExport><DependentFilesPath>mp-Dimension</DependentFilesPath><PaletteSets><PaletteSetData><PaletteSetContent><Palettes><PaletteData><PaletteContent><Palette Revision="24.1.1" option="0"><ItemID idValue="{EEF93CB5-6FDF-4FF7-BC12-5242EBE2EBEA}"/><Properties><ItemName>mp-Dimension</ItemName><Images option="0"/></Properties><Tools><Tool Revision="24.1.1" option="0"><ItemID idValue="{E2423FA4-BA4C-4A4C-A3CB-31976DE0B4B5}"/><Properties><ItemName>Linear</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_DIMLIN" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_DIMLIN" src="%ProgramBtnRes%"/></Images><Description>Creates a linear dimension</Description><Time createdUniversalDateTime="2022-02-14T04:44:14" modifiedUniversalDateTime="2022-02-14T04:44:14"/></Properties><CustomData>
											<AcRxClassInfo className="AcDbRotatedDimension"/>
											<ToolbarButton idButton="ID_Dimlinear"/>
										</CustomData>
										<ToolType>2</ToolType><Flyout enable="true"><ShapePackage idValue="{1C0B9364-5C7A-4DAC-B6B1-E9CEF007A433}"/><CurrentShape idValue="{9CBF0BA0-1B71-4244-9FAB-CF3714CF3940}"/></Flyout><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_dimlinear ]]></Macro></Command></Data>
									</Tool><Tool Revision="24.1.1" option="0"><ItemID idValue="{4AE37FEC-2DF2-4427-9A04-0C8A89589F62}"/><Properties><ItemName>Aligned</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_DIMALI" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_DIMALI" src="%ProgramBtnRes%"/></Images><Description>Creates an aligned linear dimension</Description><Time createdUniversalDateTime="2022-02-14T04:44:14" modifiedUniversalDateTime="2022-02-14T04:44:14"/></Properties><CustomData>
											<AcRxClassInfo className="AcDbAlignedDimension"/>
											<ToolbarButton idButton="ID_Dimaligne"/>
										</CustomData>
										<ToolType>2</ToolType><Flyout enable="true"><ShapePackage idValue="{1C0B9364-5C7A-4DAC-B6B1-E9CEF007A433}"/><CurrentShape idValue="{0B69DF78-4829-4BB7-9961-F0F2482BC832}"/></Flyout><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_dimaligned ]]></Macro></Command></Data>
									</Tool><Tool Revision="24.1.1" option="0"><ItemID idValue="{AA476FC3-3F7A-4540-9248-F04CF1752EEF}"/><Properties><ItemName>Arc Length</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_DIMARC" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_DIMARC" src="%ProgramBtnRes%"/></Images><Description>Creates an arc length dimension</Description><Time createdUniversalDateTime="2022-02-14T04:44:14" modifiedUniversalDateTime="2022-02-14T04:44:14"/></Properties><CustomData>
											<AcRxClassInfo className="AcDbArcDimension"/>
											<ToolbarButton idButton="ID_Dimarclen"/>
										</CustomData>
										<ToolType>2</ToolType><Flyout enable="true"><ShapePackage idValue="{1C0B9364-5C7A-4DAC-B6B1-E9CEF007A433}"/><CurrentShape idValue="{BCD90881-1A8C-48C3-B360-A2C27B82C653}"/></Flyout><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_dimarc ]]></Macro></Command></Data>
									</Tool><Tool Revision="24.1.1" option="0"><ItemID idValue="{41E2EBD3-D301-4FE0-A87C-A042D416BA76}"/><Properties><ItemName>Radius</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_DIMRAD" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_DIMRAD" src="%ProgramBtnRes%"/></Images><Description>Creates a radius dimension for a circle or an arc</Description><Time createdUniversalDateTime="2022-02-14T04:44:14" modifiedUniversalDateTime="2022-02-14T04:44:14"/></Properties><CustomData>
											<AcRxClassInfo className="AcDbRadialDimension"/>
											<ToolbarButton idButton="ID_Dimradius"/>
										</CustomData>
										<ToolType>2</ToolType><Flyout enable="true"><ShapePackage idValue="{1C0B9364-5C7A-4DAC-B6B1-E9CEF007A433}"/><CurrentShape idValue="{DC8CAAD5-47DF-4F00-AB0D-BF10574D1593}"/></Flyout><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_dimradius ]]></Macro></Command></Data>
									</Tool><Tool Revision="24.1.1" option="0"><ItemID idValue="{95C645DD-FB17-48D8-BFF8-780B4B335FB1}"/><Properties><ItemName>Diameter</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_DIMDIA" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_DIMDIA" src="%ProgramBtnRes%"/></Images><Description>Creates a diameter dimension for a circle or an arc</Description><Time createdUniversalDateTime="2022-02-14T04:44:14" modifiedUniversalDateTime="2022-02-14T04:44:14"/></Properties><CustomData>
											<AcRxClassInfo className="AcDbDiametricDimension"/>
											<ToolbarButton idButton="ID_Dimdiamet"/>
										</CustomData>
										<ToolType>2</ToolType><Flyout enable="true"><ShapePackage idValue="{1C0B9364-5C7A-4DAC-B6B1-E9CEF007A433}"/><CurrentShape idValue="{2EB7F51E-4C10-4D01-B1F9-9E01ABE737E3}"/></Flyout><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_dimdiameter ]]></Macro></Command></Data>
									</Tool><Tool Revision="24.1.1" option="0"><ItemID idValue="{49928219-71DD-4312-A184-358D2A31B13A}"/><Properties><ItemName>Angular</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_DIMANG" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_DIMANG" src="%ProgramBtnRes%"/></Images><Description>Creates an angular dimension</Description><Time createdUniversalDateTime="2022-02-14T04:44:14" modifiedUniversalDateTime="2022-02-14T04:44:14"/></Properties><CustomData>
											<AcRxClassInfo className="AcDb3PointAngularDimension"/>
											<ToolbarButton idButton="ID_Dimangula"/>
										</CustomData>
										<ToolType>2</ToolType><Flyout enable="true"><ShapePackage idValue="{1C0B9364-5C7A-4DAC-B6B1-E9CEF007A433}"/><CurrentShape idValue="{B765EEFB-C91B-47CC-A4DC-6CA08F9AF648}"/></Flyout><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_dimangular ]]></Macro></Command></Data>
									</Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{6AF8BB84-2A97-4B94-85BB-EBDA97D82944}"/><Properties><ItemName>Center Mark</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_DIMCEN" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_DIMCEN" src="%ProgramBtnRes%"/></Images><Description>Creates the center mark or the centerlines of circles and arcs</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_dimcenter ]]></Macro></Command></Data></Tool></Tools></Palette></PaletteContent><PaletteUI><CAdUiPalette PaletteStyle="1"/><CAcTcUiToolPalette><CatalogView ID="{EEF93CB5-6FDF-4FF7-BC12-5242EBE2EBEA}"><ToolSource><Palette ID="{EEF93CB5-6FDF-4FF7-BC12-5242EBE2EBEA}">mp-Dimension</Palette></ToolSource><Image SizeCX="32" SizeCY="32"/><Style>493570</Style><ToolOrder><Tool ID="{E2423FA4-BA4C-4A4C-A3CB-31976DE0B4B5}"/><Tool ID="{4AE37FEC-2DF2-4427-9A04-0C8A89589F62}"/><Tool ID="{AA476FC3-3F7A-4540-9248-F04CF1752EEF}"/><Tool ID="{41E2EBD3-D301-4FE0-A87C-A042D416BA76}"/><Tool ID="{95C645DD-FB17-48D8-BFF8-780B4B335FB1}"/><Tool ID="{49928219-71DD-4312-A184-358D2A31B13A}"/><Tool ID="{6AF8BB84-2A97-4B94-85BB-EBDA97D82944}"/></ToolOrder></CatalogView></CAcTcUiToolPalette></PaletteUI></PaletteData></Palettes></PaletteSetContent><PaletteSetUI><CAdUiDockControlBar Orientation="59420" AllowDocking="1"><FloatInfo Left="20" Top="-642" Width="172" Height="599"/><DockInfo Left="-1" Top="-789" Width="172" Height="719" MRUDockID="59420"/></CAdUiDockControlBar><CAdUiPaletteSet ActivePaletteIndex="0" TitleBarLocation="0" AutoRollup="0" Name="Tool Palettes - My Palette" Style="4222" Opacity="100" RolloverOpacity="100" Visible="1"/></PaletteSetUI></PaletteSetData></PaletteSets></ToolPaletteExport>
