<ToolPaletteExport><DependentFilesPath>mp-Draw</DependentFilesPath><PaletteSets><PaletteSetData><PaletteSetContent><Palettes><PaletteData><PaletteContent><Palette Revision="24.1.1" option="0"><ItemID idValue="{D0CC3CDC-CF6D-42EC-885C-766B8A4425EB}"/><Properties><ItemName>mp-Draw</ItemName><Images option="0"/></Properties><Tools><Tool Revision="24.1.1" option="0"><ItemID idValue="{850C2539-F4E6-493E-B82E-3E111B5DC07D}"/><Properties><ItemName>Line</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_LINE" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_LINE" src="%ProgramBtnRes%"/></Images><Description>Creates straight line segments</Description><Time createdUniversalDateTime="2022-02-14T04:44:14" modifiedUniversalDateTime="2022-02-14T04:44:14"/></Properties><CustomData>
											<AcRxClassInfo className="AcDbLine"/>
											<ToolbarButton idButton="ID_Line"/>
										</CustomData>
										<ToolType>2</ToolType><Flyout enable="true"><ShapePackage idValue="{4AFD3A7B-127C-468D-9DAD-D6D948BA8615}"/><CurrentShape idValue="{A7FC31D7-54EB-4CC8-B5D8-539D51522D1A}"/></Flyout><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_line ]]></Macro></Command></Data>
									</Tool><Tool Revision="24.1.1" option="0"><ItemID idValue="{8728DC6B-7FE1-45EC-9A09-AD278F63066E}"/><Properties><ItemName>Construction Line</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_XLINE" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_XLINE" src="%ProgramBtnRes%"/></Images><Description>Creates a line of infinite length</Description><Time createdUniversalDateTime="2022-02-14T04:44:14" modifiedUniversalDateTime="2022-02-14T04:44:14"/></Properties><CustomData>
											<AcRxClassInfo className="AcDbXline"/>
											<ToolbarButton idButton="ID_Xline"/>
										</CustomData>
										<ToolType>2</ToolType><Flyout enable="true"><ShapePackage idValue="{4AFD3A7B-127C-468D-9DAD-D6D948BA8615}"/><CurrentShape idValue="{25BB7D34-0E8F-4A36-B852-AEA08205923E}"/></Flyout><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_xline ]]></Macro></Command></Data>
									</Tool><Tool Revision="24.1.1" option="0"><ItemID idValue="{2F0D96EF-DBDC-4A67-85F8-126E9CFB3F38}"/><Properties><ItemName>Polyline</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_PLINE" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_PLINE" src="%ProgramBtnRes%"/></Images><Description>Creates a 2D polyline</Description><Time createdUniversalDateTime="2022-02-14T04:44:14" modifiedUniversalDateTime="2022-02-14T04:44:14"/></Properties><CustomData>
											<AcRxClassInfo className="AcDb2dPolyline"/>
											<ToolbarButton idButton="ID_Pline"/>
										</CustomData>
										<ToolType>2</ToolType><Flyout enable="true"><ShapePackage idValue="{4AFD3A7B-127C-468D-9DAD-D6D948BA8615}"/><CurrentShape idValue="{63B4EA09-B9B3-45BC-B864-E7A22A7EFAF2}"/></Flyout><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_pline ]]></Macro></Command></Data>
									</Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{03DE24A5-B6D6-4FCA-8E55-BB5C513F0C70}"/><Properties><ItemName>Polygon</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_POLYGO" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_POLYGO" src="%ProgramBtnRes%"/></Images><Description>Creates an equilateral closed polyline</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_polygon ]]></Macro></Command></Data></Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{2ABC3FAA-EFB3-4A8E-88E4-FBE1ECC054C6}"/><Properties><ItemName>Rectangle</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_RECTAN" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_RECTAN" src="%ProgramBtnRes%"/></Images><Description>Creates a rectangular polyline</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_rectang ]]></Macro></Command></Data></Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{291E36EC-5532-4AAC-A290-28C2E813F6FB}"/><Properties><ItemName>Arc</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_ARC3PT" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_ARC3PT" src="%ProgramBtnRes%"/></Images><Description>Creates an arc using three points</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_arc ]]></Macro></Command></Data></Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{E784812C-2F5E-416A-ABE5-E58412ABA8DB}"/><Properties><ItemName>Circle</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_CIRRAD" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_CIRRAD" src="%ProgramBtnRes%"/></Images><Description>Creates a circle using a center point and a radius</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_circle ]]></Macro></Command></Data></Tool><Tool Revision="24.1.1" option="0"><ItemID idValue="{C8845D46-13B7-4FA4-AB74-1B8FA64821DE}"/><Properties><ItemName>Spline</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_SPLINE" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_SPLINE" src="%ProgramBtnRes%"/></Images><Description>Creates a smooth curve that passes through or near specified points</Description><Time createdUniversalDateTime="2022-02-14T04:44:14" modifiedUniversalDateTime="2022-02-14T04:44:14"/></Properties><CustomData>
											<AcRxClassInfo className="AcDbSpline"/>
											<ToolbarButton idButton="ID_Spline"/>
										</CustomData>
										<ToolType>2</ToolType><Flyout enable="true"><ShapePackage idValue="{4AFD3A7B-127C-468D-9DAD-D6D948BA8615}"/><CurrentShape idValue="{9E94EFA7-423D-4CED-AC1C-889A7BE3906B}"/></Flyout><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C^R_spline ]]></Macro></Command></Data>
									</Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{79292B79-DE42-40E0-8112-9A3B12248F44}"/><Properties><ItemName>Ellipse</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_ELLAE" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_ELLAE" src="%ProgramBtnRes%"/></Images><Description>Creates an ellipse or an elliptical arc</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_ellipse ]]></Macro></Command></Data></Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{24D0386F-AB8B-42AC-AA5E-5643652E1084}"/><Properties><ItemName>Ellipse Arc</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_ELLARC" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_ELLARC" src="%ProgramBtnRes%"/></Images><Description>Creates an elliptical arc</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_ellipse _a ]]></Macro></Command></Data></Tool></Tools></Palette></PaletteContent><PaletteUI><CAdUiPalette PaletteStyle="1"/><CAcTcUiToolPalette><CatalogView ID="{D0CC3CDC-CF6D-42EC-885C-766B8A4425EB}"><ToolSource><Palette ID="{D0CC3CDC-CF6D-42EC-885C-766B8A4425EB}">mp-Draw</Palette></ToolSource><Image SizeCX="32" SizeCY="32"/><Style>493570</Style><ToolOrder><Tool ID="{850C2539-F4E6-493E-B82E-3E111B5DC07D}"/><Tool ID="{8728DC6B-7FE1-45EC-9A09-AD278F63066E}"/><Tool ID="{2F0D96EF-DBDC-4A67-85F8-126E9CFB3F38}"/><Tool ID="{03DE24A5-B6D6-4FCA-8E55-BB5C513F0C70}"/><Tool ID="{2ABC3FAA-EFB3-4A8E-88E4-FBE1ECC054C6}"/><Tool ID="{291E36EC-5532-4AAC-A290-28C2E813F6FB}"/><Tool ID="{E784812C-2F5E-416A-ABE5-E58412ABA8DB}"/><Tool ID="{C8845D46-13B7-4FA4-AB74-1B8FA64821DE}"/><Tool ID="{79292B79-DE42-40E0-8112-9A3B12248F44}"/><Tool ID="{24D0386F-AB8B-42AC-AA5E-5643652E1084}"/></ToolOrder></CatalogView></CAcTcUiToolPalette></PaletteUI></PaletteData></Palettes></PaletteSetContent><PaletteSetUI><CAdUiDockControlBar Orientation="59420" AllowDocking="1"><FloatInfo Left="20" Top="-642" Width="172" Height="599"/><DockInfo Left="-1" Top="-789" Width="172" Height="719" MRUDockID="59420"/></CAdUiDockControlBar><CAdUiPaletteSet ActivePaletteIndex="0" TitleBarLocation="0" AutoRollup="0" Name="Tool Palettes - My Palette" Style="4222" Opacity="100" RolloverOpacity="100" Visible="1"/></PaletteSetUI></PaletteSetData></PaletteSets></ToolPaletteExport>
