<ToolPaletteExport><DependentFilesPath>mp-Favorites</DependentFilesPath><PaletteSets><PaletteSetData><PaletteSetContent><Palettes><PaletteData><PaletteContent><Palette Revision="24.1.1" option="0"><ItemID idValue="{093AD8DA-D66C-484B-AE6E-3BEF69D31945}"/><Properties><ItemName>mp-Favorites</ItemName><Images option="0"/></Properties><Tools><Tool Revision="24.1.1" option="0"><ItemID idValue="{74F566A2-DC4D-4A0A-90C6-8BA062A8CDDF}"/><Properties><ItemName>Line</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_LINE" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_LINE" src="%ProgramBtnRes%"/></Images><Description>Creates straight line segments</Description><Time createdUniversalDateTime="2022-02-17T22:35:53" modifiedUniversalDateTime="2022-02-17T22:35:53"/></Properties><CustomData>
											<AcRxClassInfo className="AcDbLine"/>
											<ToolbarButton idButton="ID_Line"/>
										</CustomData>
										<ToolType>2</ToolType><Flyout enable="true"><ShapePackage idValue="{4AFD3A7B-127C-468D-9DAD-D6D948BA8615}"/><CurrentShape idValue="{A7FC31D7-54EB-4CC8-B5D8-539D51522D1A}"/></Flyout><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_line ]]></Macro></Command></Data>
									</Tool><Tool Revision="24.1.1" option="0"><ItemID idValue="{D22A630D-6EE2-43C5-B7E9-3678D49A5526}"/><Properties><ItemName>Construction Line</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_XLINE" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_XLINE" src="%ProgramBtnRes%"/></Images><Description>Creates a line of infinite length</Description><Time createdUniversalDateTime="2022-02-17T22:35:53" modifiedUniversalDateTime="2022-02-17T22:35:53"/></Properties><CustomData>
											<AcRxClassInfo className="AcDbXline"/>
											<ToolbarButton idButton="ID_Xline"/>
										</CustomData>
										<ToolType>2</ToolType><Flyout enable="true"><ShapePackage idValue="{4AFD3A7B-127C-468D-9DAD-D6D948BA8615}"/><CurrentShape idValue="{25BB7D34-0E8F-4A36-B852-AEA08205923E}"/></Flyout><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_xline ]]></Macro></Command></Data>
									</Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{6D7B1EAA-0E97-463A-A064-332B65AE25DA}"/><Properties><ItemName>Rectangle</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_RECTAN" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_RECTAN" src="%ProgramBtnRes%"/></Images><Description>Creates a rectangular polyline</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_rectang ]]></Macro></Command></Data></Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{AB608DB9-C506-4E6C-89A0-DD7AA80F2768}"/><Properties><ItemName>Arc</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_ARC3PT" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_ARC3PT" src="%ProgramBtnRes%"/></Images><Description>Creates an arc using three points</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_arc ]]></Macro></Command></Data></Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{A142FAE4-9044-4064-AA38-8B067BEF2D4A}"/><Properties><ItemName>Circle</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_CIRRAD" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_CIRRAD" src="%ProgramBtnRes%"/></Images><Description>Creates a circle using a center point and a radius</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_circle ]]></Macro></Command></Data></Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{AE69FA06-6507-4313-8404-5C6CACF1B816}"/><Properties><ItemName>Ellipse</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_ELLAE" src="%ProgramBtnRes%"/></Images><Description>Creates an ellipse or an elliptical arc</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_ellipse ]]></Macro></Command></Data></Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{8F9D81B1-FDE0-4961-B3D2-EEBB92D6676A}"/><Properties><ItemName>Center Mark</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_DIMCEN" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_DIMCEN" src="%ProgramBtnRes%"/></Images><Description>Creates the center mark or the centerlines of circles and arcs</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_dimcenter ]]></Macro></Command></Data></Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{7A9CE028-2A84-419A-93CA-83803DCE2310}"/><Properties><ItemName>Erase</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_ERASE" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_ERASE" src="%ProgramBtnRes%"/></Images><Description>Removes objects from a drawing</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_erase ]]></Macro></Command></Data></Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{A0B56CF7-CA16-46B6-8F8A-9FC5F16B8268}"/><Properties><ItemName>Offset</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_OFFSET" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_OFFSET" src="%ProgramBtnRes%"/></Images><Description>Creates concentric circles, parallel lines, and parallel curves</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_offset ]]></Macro></Command></Data></Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{923BC0AA-F3A7-4B8C-8EED-02ADBF24D78E}"/><Properties><ItemName>Move</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_MOVE" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_MOVE" src="%ProgramBtnRes%"/></Images><Description>Moves objects a specified distance in a specified direction</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[$M=$(if,$(eq,$(substr,$(getvar,cmdnames),1,4),GRIP),_move,^C^C_move) ]]></Macro></Command></Data></Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{B19CF2D2-0015-463E-B9A8-28E27148B844}"/><Properties><ItemName>Rotate</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_ROTATE" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_ROTATE" src="%ProgramBtnRes%"/></Images><Description>Rotates objects around a base point </Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[$M=$(if,$(eq,$(substr,$(getvar,cmdnames),1,4),GRIP),_rotate,^C^C_rotate) ]]></Macro></Command></Data></Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{213637BA-DFA4-4C03-8E49-0BA5ABC54AF2}"/><Properties><ItemName>Extend</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_EXTEND" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_EXTEND" src="%ProgramBtnRes%"/></Images><Description>Extends objects to meet the edges of other objects</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_extend ]]></Macro></Command></Data></Tool><Tool Revision="24.1.1" option="24"><ItemID idValue="{B87AFB26-9918-4713-9916-243D5D7C1185}"/><Properties><ItemName>Fillet</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_FILLET" src="%ProgramBtnRes%"/><Image cx="20" cy="20" IsDark="true" resource="RCDATA_16_FILLET" src="%ProgramBtnRes%"/></Images><Description>Rounds and fillets the edges of objects</Description><Time createdUniversalDateTime="2022-02-14T04:34:52" modifiedUniversalDateTime="2022-02-14T04:34:52"/></Properties><ToolType>1</ToolType><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data><GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_fillet ]]></Macro></Command></Data></Tool><Tool Revision="24.1.1" option="0"><ItemID idValue="{09DD8B95-6D24-4676-BCC6-779B538F7C40}"/><Properties><ItemName>Linear</ItemName><Images option="0"><Image cx="20" cy="20" IsDark="false" resource="RCDATA_16_DIMLIN" src="%ProgramBtnRes%"/></Images><Description>Creates a linear dimension</Description><Time createdUniversalDateTime="2022-03-01T00:22:49" modifiedUniversalDateTime="2022-03-01T00:22:49"/></Properties><CustomData>
											<AcRxClassInfo className="AcDbRotatedDimension"/>
											<ToolbarButton idButton="ID_Dimlinear"/>
										</CustomData>
										<ToolType>2</ToolType><Flyout enable="true"><ShapePackage idValue="{1C0B9364-5C7A-4DAC-B6B1-E9CEF007A433}"/><CurrentShape idValue="{9CBF0BA0-1B71-4244-9FAB-CF3714CF3940}"/></Flyout><StockToolRef idValue="{2AE7120B-CEE4-47A5-9B50-EF9F3ADE24AC}"/><Data>
											<GeneralProperties><Color><BasicPropInfo><PropValue unspecified="TRUE"/></BasicPropInfo></Color><Layer><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Layer><Linetype><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Linetype><LinetypeScale><BasicPropInfo><PropValue unspecified="TRUE" valueType="3" value="0"/></BasicPropInfo></LinetypeScale><PlotStyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></PlotStyle><LineWeight><BasicPropInfo><PropValue unspecified="TRUE" valueType="2" value="0"/></BasicPropInfo></LineWeight><Transparency><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Transparency><Textstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Textstyle><Dimstyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Dimstyle><Tablestyle><BasicPropInfo><PropValue unspecified="TRUE" valueType="1"/></BasicPropInfo></Tablestyle></GeneralProperties><Command><Macro><![CDATA[^C^C_dimlinear ]]></Macro></Command></Data>
									</Tool></Tools></Palette></PaletteContent><PaletteUI><CAdUiPalette PaletteStyle="1"/><CAcTcUiToolPalette><CatalogView ID="{093AD8DA-D66C-484B-AE6E-3BEF69D31945}"><ToolSource><Palette ID="{093AD8DA-D66C-484B-AE6E-3BEF69D31945}">mp-Favorites</Palette></ToolSource><Image SizeCX="32" SizeCY="32"/><Style>493570</Style><ToolOrder><Tool ID="{74F566A2-DC4D-4A0A-90C6-8BA062A8CDDF}"/><Tool ID="{D22A630D-6EE2-43C5-B7E9-3678D49A5526}"/><Tool ID="{6D7B1EAA-0E97-463A-A064-332B65AE25DA}"/><Tool ID="{AB608DB9-C506-4E6C-89A0-DD7AA80F2768}"/><Tool ID="{A142FAE4-9044-4064-AA38-8B067BEF2D4A}"/><Tool ID="{AE69FA06-6507-4313-8404-5C6CACF1B816}"/><Tool ID="{8F9D81B1-FDE0-4961-B3D2-EEBB92D6676A}"/><Tool ID="{7A9CE028-2A84-419A-93CA-83803DCE2310}"/><Tool ID="{A0B56CF7-CA16-46B6-8F8A-9FC5F16B8268}"/><Tool ID="{923BC0AA-F3A7-4B8C-8EED-02ADBF24D78E}"/><Tool ID="{B19CF2D2-0015-463E-B9A8-28E27148B844}"/><Tool ID="{213637BA-DFA4-4C03-8E49-0BA5ABC54AF2}"/><Tool ID="{B87AFB26-9918-4713-9916-243D5D7C1185}"/><Tool ID="{09DD8B95-6D24-4676-BCC6-779B538F7C40}"/></ToolOrder></CatalogView></CAcTcUiToolPalette></PaletteUI></PaletteData></Palettes></PaletteSetContent><PaletteSetUI><CAdUiDockControlBar Orientation="59420" AllowDocking="1"><FloatInfo Left="35" Top="66" Width="172" Height="599"/><DockInfo Left="3" Top="77" Width="300" Height="693" MRUDockID="59420"/></CAdUiDockControlBar><CAdUiPaletteSet ActivePaletteIndex="0" TitleBarLocation="0" AutoRollup="0" Name="Tool Palettes - My Palette" Style="4222" Opacity="100" RolloverOpacity="100" Visible="1"/></PaletteSetUI></PaletteSetData></PaletteSets></ToolPaletteExport>
